app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::get('/', 'HomeController@welcome');
    Route::auth();
    Route::get('/home', 'HomeController@index');
    Route::resource('products', 'ProductsController');
    Route::get('catalogs', 'CatalogsController@index');
    Route::resource('categories', 'CategoriesController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['title', 'parent_id'];

    public static function boot()
    {
        parent::boot();

        static::deleting(function($model) {
            // remove parent from this category's child
            foreach ($model->childs as $child) {
                $child->parent_id = '';
                $child->save();
            }
            // remove relations to products
            $model->products()->detach();
        });
    }

    public function childs()
    {
        return $this->hasMany('App\Category', 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo('App\Category', 'parent_id');
    }

    public function products()
    {
        return $this->belongsToMany('App\Product');
    }

    /**
     * Get total amount of product from current category and its child
     * @return int
     */
    public function getTotalProductsAttribute()
    {
        return Product::whereIn('id', $this->related_products_id)->count();
    }

    /**
     * Get all product id from active category and its child
     */
    public function getRelatedProductsIdAttribute()
    {
        $result = $this->products->lists('id')->toArray();
        foreach ($this->childs as $child) {
            $result = array_merge($result, $child->related_products_id);
        }
        return $result;
    }
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'photo', 'model'];

    public static function boot()
    {
        parent::boot();

        static::deleting(function($model) {
            // remove relations to category
            $model->categories()->detach();
        });
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }

    public function getCategoryListsAttribute()
    {
        if ($this->categories()->count() < 1) {
            return null;
        }
        return $this->categories->lists('id')->all();
    }

    /**
     * Get path to product photo or give placeholder if its not set
     * @return string
     */
    public function getPhotoPathAttribute()
    {
        if ($this->photo !== '') {
            return url('/img/' . $this->photo);
        } else {
            return 'http://placehold.it/850x618';
        }
    }
}

app/Http/Controllers/CatalogsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Product;
use App\Category;

class CatalogsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $q = $request->get('q');
        if ($request->has('cat')) {
            $selected_category = Category::find($request->get('cat'));

            // can't use this to get selected category > child's > product
            // $products = $selected_category->products()->where('name', 'LIKE', '%'.$q.'%')->paginate(4);

            // we use this to get product from current category and its child
            $products = Product::whereIn('id', $selected_category->related_products_id)
                ->where('name', 'LIKE', '%'.$q.'%')->paginate(4);
        } else {
            $products = Product::where('name', 'LIKE', '%'.$q.'%')->paginate(4);
        }

        return view('catalogs.index', compact('products', 'q', 'cat', 'selected_category'));
    }
}

resources/views/catalogs/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Search products</h3>
          </div>
          <div class="panel-body">
            {!! Form::open(['url' => 'catalogs', 'method'=>'get']) !!}
                <div class="form-group {!! $errors->has('q') ? 'has-error' : '' !!}">
                  {!! Form::label('q', 'What are you looking for?') !!}
                  {!! Form::text('q', isset($q) ? $q : null, ['class'=>'form-control']) !!}
                  {!! $errors->first('q', '<p class="help-block">:message</p>') !!}
                </div>

                {!! Form::hidden('cat', isset($selected_category) ? $selected_category->id : '') !!}

              {!! Form::submit('Search', ['class'=>'btn btn-primary']) !!}
            {!! Form::close() !!}
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Filter by category</h3>
          </div>
          <ul class="nav nav-pills nav-stacked">
            <li ><a href="/catalogs">All Products</a></li>
            @foreach(App\Category::all() as $category)
              <li ><a href="{{ url('/catalogs?cat=' . $category->id)}}">{{ $category->title }}
              {{ $category->total_products > 0 ? '(' . $category->total_products . ')' : ''}}</a></li>
            @endforeach
          </ul>
        </div>
      </div>
      <div class="col-md-9">
        <div class="row">
          <div class="col-md-12"><h1>Category : {{ isset($selected_category) ? $selected_category->title : 'All'}}</h1></div>
          @forelse ($products as $product)
            <div class="col-md-6">
              <h3>{{ $product->name }}</h3>
              <div class="thumbnail">
                <img src="{{ $product->photo_path }}" class="img-rounded">
                  <p>Model: {{ $product->model }}</p>
                  <p>Category:
                    @foreach ($product->categories as $category)
                      <a href="{{ url('/catalogs?cat=' . $category->id)}}">
                        <span class="label label-primary">
                        <i class="fa fa-btn fa-tags"></i>
                        {{ $category->title }}</span>
                      </a>
                    @endforeach
                  </p>
              </div>
            </div>
          @empty
            <div class="col-md-12 text-center">
              <h1>:(</h1>
              <p>We can't find what you're looking for.</p>
            </div>
          @endforelse


          <div class="pull-right">{!! $products->links() !!}</div>
        </div>
      </div>
    </div>
  </div>



@endsection